TYPE_ADDED = 0
TYPE_UPDATED = 1
TYPE_DELETED = 2
TYPE_DELETED_CASCADE = 3
TYPE_REVERTED = 4
TYPE_REVERTED_ADDED = 5
TYPE_REVERTED_DELETED = 6
TYPE_REVERTED_DELETED_CASCADE = 7
TYPE_CHOICES = (
    (TYPE_ADDED, 'Added'),
    (TYPE_UPDATED, 'Updated'),
    (TYPE_DELETED, 'Deleted'),
    (TYPE_DELETED_CASCADE, 'Deleted via cascade'),
    (TYPE_REVERTED, 'Reverted'),
    (TYPE_REVERTED_ADDED, 'Reverted/Added'),
    (TYPE_REVERTED_DELETED, 'Reverted/Deleted'),
    (TYPE_REVERTED_DELETED_CASCADE, 'Reverted/Deleted via cascade'),
)
